name: Build and Push Frontend Docker Image to GHCR!

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Frontend to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      STRAPI_INTERNAL_URL: ${{ vars.STRAPI_BUILD_URL }}
      NEXT_PUBLIC_STRAPI_API_URL: ${{ vars.STRAPI_BUILD_URL }}/api  # Adjust if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify environment variables
        run: |
          echo "STRAPI_INTERNAL_URL=$STRAPI_INTERNAL_URL"
          echo "NEXT_PUBLIC_STRAPI_API_URL=$NEXT_PUBLIC_STRAPI_API_URL"
          if [ -z "$STRAPI_INTERNAL_URL" ]; then
            echo "Error: STRAPI_INTERNAL_URL is not set"
            exit 1
          fi
        env:
          STRAPI_INTERNAL_URL: ${{ vars.STRAPI_BUILD_URL }}
          NEXT_PUBLIC_STRAPI_API_URL: ${{ vars.STRAPI_BUILD_URL }}/api          

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          no-cache: true  # Prevent cache issues
          tags: |
            ghcr.io/oarthurfc/blog-gol-frontend:latest
          build-args: |
            STRAPI_INTERNAL_URL=${{ env.STRAPI_INTERNAL_URL }}
            NEXT_PUBLIC_STRAPI_API_URL=${{ env.NEXT_PUBLIC_STRAPI_API_URL }}